import { createEnv } from "@t3-oss/env-core";
import { ADDRESS, ONLY_BOOLEAN, STRING_NOT_EMPTY } from "./zod";

export const envs = createEnv({
  clientPrefix: "NEXT_PUBLIC_",

  client: {
    // RainbowKit
    NEXT_PUBLIC_RAINBOWKIT_PROJECT_ID: STRING_NOT_EMPTY,
    NEXT_PUBLIC_ETHEREUM_MAINNET_RPC_URL: STRING_NOT_EMPTY,

    // Tenderly
    NEXT_PUBLIC_TENDERLY_PROJECT_ID: STRING_NOT_EMPTY,
    NEXT_PUBLIC_TENDERLY_VNETS_ENABLED: ONLY_BOOLEAN,
    NEXT_PUBLIC_ENABLE_TESTNETS: ONLY_BOOLEAN,

    // Etherscan
    NEXT_PUBLIC_ETHERSCAN_API_KEY: STRING_NOT_EMPTY,

    // Contract Addresses
    NEXT_PUBLIC_META_MORPHO_FACTORY_ADDRESS: ADDRESS,
    NEXT_PUBLIC_META_MORPHO_ADDRESS: ADDRESS,
  },
  runtimeEnvStrict: {
    // RainbowKit
    NEXT_PUBLIC_RAINBOWKIT_PROJECT_ID:
      process.env.NEXT_PUBLIC_RAINBOWKIT_PROJECT_ID,
    NEXT_PUBLIC_ETHEREUM_MAINNET_RPC_URL:
      process.env.NEXT_PUBLIC_ETHEREUM_MAINNET_RPC_URL,

    // Tenderly
    NEXT_PUBLIC_TENDERLY_PROJECT_ID:
      process.env.NEXT_PUBLIC_TENDERLY_PROJECT_ID,
    NEXT_PUBLIC_TENDERLY_VNETS_ENABLED:
      process.env.NEXT_PUBLIC_TENDERLY_VNETS_ENABLED,
    NEXT_PUBLIC_ENABLE_TESTNETS: process.env.NEXT_PUBLIC_ENABLE_TESTNETS,

    // Etherscan
    NEXT_PUBLIC_ETHERSCAN_API_KEY: process.env.NEXT_PUBLIC_ETHERSCAN_API_KEY,

    // Contract Addresses
    NEXT_PUBLIC_META_MORPHO_FACTORY_ADDRESS:
      process.env.NEXT_PUBLIC_META_MORPHO_FACTORY_ADDRESS,
    NEXT_PUBLIC_META_MORPHO_ADDRESS:
      process.env.NEXT_PUBLIC_META_MORPHO_ADDRESS,
  },
  emptyStringAsUndefined: true,
});
