name: CI/CD Production
on:
  release:
    types: [created]
permissions:
  contents: write
jobs:
  merge-to-production:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: main

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Determine Release Name
        id: release_name
        run: |
          RELEASE_NAME="${{ github.event.release.name }}"
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV

      - name: Fetch all branches
        run: git fetch --all

      - name: Force Push Main to Production with Release Name
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout production
          git reset --hard main
          git push --force origin production
